[workspace]

resolver = "3"
members = ["crates/seruq-core", "crates/seruq-runtime", "crates/seruq-platform-winit"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/naoshinn/seruq"

[workspace.dependencies]
seruq-core = { version = "0.1.0", path = "crates/seruq-core" }
thiserror = "2"

[workspace.lints.rust]
unsafe_code = "deny"
